### ISSUE TITLE
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by Soooooda69** [nerf2nerf/nerf2nerf#1]
I got the error 'RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.' when I'm running `python main.py --yaml bust`. The iterations are good, the error happened when rendering images. Btw, do you have any script to allow generating my own scenes for registration? Thanks!

> Traceback (most recent call last):
  File "main.py", line 184, in <module>
    image_size=opt.image_size, near=opt.near, far=opt.far, chunk=opt.chunk)
  File "/content/drive/MyDrive/nerf2nerf/utils.py", line 215, in show
    rgb1 = nerf1.render_image_fine((s).unsqueeze(0).to(device).float(), focal_length=focal, scale=1, near=near, far=far, chunk=chunk)
  File "/content/drive/MyDrive/nerf2nerf/nerf_wrapper.py", line 129, in render_image_fine
    torch.tensor(far).to(device))
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/model/nerf/___torch_mangle_75.py", line 102, in trace_eval
    _23 = torch.mul(torch.unsqueeze(_22, 1), torch.unsqueeze(depth0, 2))
    positions = torch.add(_21, _23)
    _24 = (coarse2).forward(positions, inputs, )
           ~~~~~~~~~~~~~~~~ <--- HERE
    _25, _26, = _24
    _27 = torch.slice(depth0, 1, 1, 9223372036854775807)
  File "code/__torch__/model/nerf.py", line 58, in forward
    density0 = torch.to(density, 6)
    _6 = torch.randn_like(density0, dtype=6, layout=0, device=torch.device("cuda:0"), pin_memory=False)
    density1 = torch.add_(density0, torch.mul(_6, CONSTANTS.c7))
               ~~~~~~~~~~ <--- HERE
    sample_density = torch.softplus(density1)
    _7 = (to_radiance).forward((radiance).forward(_5, ), )

> Traceback of TorchScript, original code (most recent call last):
/home/drebain/Workspace/torch_nerf/model/nerf.py(474): query
/home/drebain/Workspace/torch_nerf/model/nerf.py(464): forward
/home/drebain/anaconda3/envs/torch_nerf/lib/python3.10/site-packages/torch/nn/modules/module.py(1092): _slow_forward
/home/drebain/anaconda3/envs/torch_nerf/lib/python3.10/site-packages/torch/nn/modules/module.py(1108): _call_impl
/home/drebain/Workspace/torch_nerf/model/nerf.py(234): trace_rays_importance
/home/drebain/Workspace/torch_nerf/model/nerf.py(512): trace_eval
/home/drebain/anaconda3/envs/torch_nerf/lib/python3.10/site-packages/torch/jit/_trace.py(939): trace_module
/home/drebain/Workspace/torch_nerf/serialize_model.py(42): main
/home/drebain/Workspace/torch_nerf/config.py(76): start_script
/home/drebain/Workspace/torch_nerf/serialize_model.py(8): <module>
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

**Comment by lilygoli** [comment]
I cannot reproduce this error. Do you also get the same error if you run `python nerf_wrapper.py`? This is just a sanity check that the wrapper works fine for you and can render images.

No, I currently do not have the script for training NeRFs and converting them to jit models. Although the NeRF model used for blender scenes is the vanilla pytorch-NeRF and can be converted to jit model after training easily.

**Comment by Soooooda69** [comment]
I got the same error with `python nerf_wrapper.py`. Is it because of my python version is 3.7?

**Comment by lilygoli** [comment]
It might be. I tested with python 3.8 and I got the same error that you reported. It works with python 3.10 and torch 1.11.0.

**Comment by cys-cys158** [comment]
I got the same error,but my python version is 3.10. Is it because of my CUDA version is 11.1?

**Comment by swtyree** [comment]
Hi, I encountered the same error after installing via the "Build Environment and Run" instructions (Python 3.10.8 and PyTorch 1.13.1). If it would be helpful to see additional output, let me know.

**Comment by jiadingfang** [comment]
same problem running the example command for bust scene. Python 3.10 and Pytorch 1.13.

**Comment by lilygoli** [comment]
Can you please include the additional outputs of the error? The problem is arising from deserializing the NeRF model dataset in PyTorch jit, and its probably because of version inconsistency. While we investigate this issue, you can run the code with python 3.10 and torch 1.11.0 which the code has been tested with to work.
