### ISSUE TITLE
how to visualize the nerf in 3d

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [nerf2nerf/nerf2nerf#10]
Hi, Lily @lilygoli,

I saw you saved all the visualization results to Tensorboard. This can only visualize the pose optimization process in 2d space. I'd like to know the Nerf visualization output. In that way, you can get a compact check of the output. Do you have any suggestions?

**Comment by lilygoli** [comment]
Hi,

You can use the visdom visualization tool included in the code that gives you 3D point cloud output and you can view it throughout the registration iterations.

**Comment by KnightOfTheMoonlight** [comment]
> 

Yes. This is a feasible option. 

I have run the `--extract_pc` option. Then there comes a new question. Where did you get the `transforms.json` file? I saw 8 camera extrinsic parameters are generated. And the selected 3d surface points are visualized as follows.  However, what do the preset extrinsic parameters contain?

![Screenshot from 2023-06-16 14-49-38](https://github.com/nerf2nerf/nerf2nerf/assets/3291902/54dab729-7773-455e-a5f2-206ceee848f7)

**Comment by lilygoli** [comment]
The transforms.json is the training image poses of the original NeRF. We assume access to original camera poses of NeRF as a soft constraint to know from which poses the NeRF can predict the scene structure best. Then we select 8 poses from the set of training poses by furthest point sampling.

**Comment by KnightOfTheMoonlight** [comment]
> The transforms.json is the training image poses of the original NeRF. We assume access to original camera poses of NeRF as a soft constraint to know from which poses the NeRF can predict the scene structure best. Then we select 8 poses from the set of training poses by furthest point sampling.

What do you mean the original NERF? Is it a predefined world coordinate? If so, where is the definition of it?

**Comment by KnightOfTheMoonlight** [comment]
> The transforms.json is the training image poses of the original NeRF. We assume access to original camera poses of NeRF as a soft constraint to know from which poses the NeRF can predict the scene structure best. Then we select 8 poses from the set of training poses by furthest point sampling.

So does the nerf coordinate the same as the following defined in the original nerf paper.
[nerf-Already have poses!](https://github.com/bmild/nerf#already-have-poses) 

```
In run_nerf.py and all other code, we use the same pose coordinate system as in OpenGL: the local camera coordinate system
 of an image is defined in a way that the X axis points to the right, the Y axis upwards, and the Z axis backwards as seen from
 the image.

Poses are stored as 3x4 numpy arrays that represent camera-to-world transformation matrices. The other data you will need is 
simple pinhole camera intrinsics (hwf = [height, width, focal length]) and near/far scene bounds. Take a look at [our data loading 
code](https://github.com/bmild/nerf/blob/master/run_nerf.py#L406) to see more.
```

**Comment by lilygoli** [comment]
yes that is correct. You can find everything you need for nerf coordinates from the transform.json
