### ISSUE TITLE
Could you share your code for nerf generation

### ISSUE THREAD

**Issue by KnightOfTheMoonlight** [nerf2nerf/nerf2nerf#11]
I am trying to run the registration for my data.

However, I am using instant-ngp for the nerf training. It's no-trivial for me to convert to your nerf wrapper.

**Comment by lilygoli** [comment]
We used [this code](https://drive.google.com/file/d/1uqLOoexKDYC7GEsMCzWHimY36tv5A1gU/view?usp=sharing) for our NeRF model. You can find the three interface methods at the bottom of the file.

**Comment by KnightOfTheMoonlight** [comment]
> We used [this code](https://drive.google.com/file/d/1uqLOoexKDYC7GEsMCzWHimY36tv5A1gU/view?usp=sharing) for our NeRF model. You can find the three interface methods at the bottom of the file.

Yes. I found this file in other issues. It is the network modelling part. But my question is how to train this. 

Is this the original nerf style modelling? Currently, I am using Instant-ngp, its network modelling is quite different from this interface. Currently, I think the volume rendering from instant-ngp is more like a frame-per-frame rendering, instead of a ray generation of radiance field from original nerf.

**Comment by lilygoli** [comment]
We used mipNeRF and mipNeRF360 style NeRFs as a backbone. I am not sure what you mean by frame-per-frame rendering. The rendering scheme at inference should be the same as original NeRF from my understanding.

**Comment by KnightOfTheMoonlight** [comment]
> We used mipNeRF and mipNeRF360 style NeRFs as a backbone. I am not sure what you mean by frame-per-frame rendering. The rendering scheme at inference should be the same as original NeRF from my understanding.

Hi, I tried to understand the training model part from [mip-nerf](url) or [mip-nerf360.](https://github.com/google-research/multinerf) However I didn't find their nerf model interface functions `call_eval` `transmittance_eval` `trace_eval`
