### ISSUE TITLE
Query about data in transforms.json

### ISSUE THREAD

**Issue by StephenHausler** [nerf2nerf/nerf2nerf#12]
Hi,
Thanks for this great work!

I've been using your work and I've got a query about the content of transforms.json (in your google drive). What images correspond to the extrinsics within transforms.json?

I also downloaded your training data from Borealis. In the zip files, I found some transforms_train.json files (one file for variant 'a' and one file for variant 'b' per scene). I've worked out that these extrinsics correspond to the training images in the same directory, but then what is the difference between the transforms.json in your google drive versus the transforms_train.json files in Borealis?

Thanks

**Comment by lilygoli** [comment]
Hi!

Sorry for the late reply, I had missed the email on this issue. The transforms.json file in the google drive is the same as the transforms_train.json in 'a' folders, with the difference that in some scenes, the scene might have been scaled down or up for better surface distillation and also to resolve any mismatch in scale difference between 'a' and 'b' scenes. The registration code uses the transforms.json file in google drive only. The transform_train.json files in Borealis (and the rest of those files) are the files used for training the NeRFs in the nerf2nerf NeRF dataset.

**Comment by StephenHausler** [comment]
Hi, thanks for your explanation, this makes sense and answers my questions.
