### ISSUE TITLE
Resolution used when training nerf2nerf models

### ISSUE THREAD

**Issue by StephenHausler** [nerf2nerf/nerf2nerf#15]
Hi!
I've got another question about your work, I was wondering what resolution to you use when training your nerf models? Do you resize the images to 512x512?

**Comment by lilygoli** [comment]
@drebain would you mind providing details on the NeRF dataset training? Thanks!

**Comment by drebain** [comment]
Every model I trained used the native resolution of the training images. It's possible the mipNeRF-360 models were trained on down-sampled images, but I don't have the code for that to check.

**Comment by StephenHausler** [comment]
I see, ok great thanks,. This helps a lot, thanks.
