### ISSUE TITLE
No output in Visdom

### ISSUE THREAD

**Issue by around-star** [nerf2nerf/nerf2nerf#3]
Hi, for the registration task, I am not getting any output in the visdom. The training is getting interrupted due to insufficient memory after a few iterations, but even for the iterations been run, shouldn't there be some output in Visdom?
![Visdom](https://user-images.githubusercontent.com/55460763/221370638-9f36de96-2f48-47e2-92ba-e21afe0e424f.png)
![Output](https://user-images.githubusercontent.com/55460763/221370671-98bb51b5-b0f3-4a77-add3-c81df5fa6d14.png)

**Comment by lilygoli** [comment]
Yes there should be a visualization as soon as the first textual log appears. Have you tried checking to see if there is another environment in the Visdom environment section? The visualizations, if using the default code, should be under an environment called "Reg" not the default "main".

**Comment by around-star** [comment]
Thanks for getting back! Yes, I switched to "Reg" env and got the visualizations.
