### ISSUE TITLE
Real scene refining surface field

### ISSUE THREAD

**Issue by Sucasx** [nerf2nerf/nerf2nerf#4]
Hello, why did I refine the surface field of scene a in the fourth pair of scenes by myself, the effect was completely unavailable to the surface field pre-training model provided by the data set, and the number of positive samples screened during the training process of the surface field was very small, There are only a few sample points, what is the problem? Is it because the labeled sampling boundary range is wrong?

**Comment by lilygoli** [comment]
Hi! Thanks for noticing this problem. 
Yes, it seems the dataset NeRFs on scenes 4 and 5 have been corrupted in the repackaging for dataset release (wrong scale). We will be updating the dataset in the next few days.

**Comment by lilygoli** [comment]
The NeRFs on scenes 4 and 5 are updated to be in the right scale on the dataset drive. Hopefully you should be able to visualize the surface now (for example you can use `show_gt_image` with level=1 in scene 4 to visualize the GT surface).
