### ISSUE TITLE
Original images

### ISSUE THREAD

**Issue by leosegre** [nerf2nerf/nerf2nerf#5]
Hi,

Can you please publish the images you used to create the NeRF?

Thanks

**Comment by lilygoli** [comment]
Hello,

You can find all the data for synthetic scenes and scene 4 here: 
https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP3/2805LG

The data for scene 5 will also be added soon.

**Comment by leosegre** [comment]
Hi,

Thanks for your response!
Can you please update when scene 5 is available too?

Thanks,
Leo

**Comment by lilygoli** [comment]
Hi Leo,
The dataset is complete now and moved to a permanent location here: https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP3/2805LG
