### ISSUE TITLE
Converting nerf to mesh/point cloud

### ISSUE THREAD

**Issue by hzyjerry** [nerf2nerf/nerf2nerf#7]
Hi, thanks for open-sourcing the project. It's very cool.

I wonder if one can use the surface field in the work to convert nerf to a mesh/point cloud? In general, what do you think is the viability of it? 

Thank you.

**Comment by lilygoli** [comment]
Hi!

I have not tried this before, but as surface fields take 3D points as input and provide surface value in the range of 0 to 1 (or binary 0-1 value if thresholded) it might need a very dense sampling method to be able to extract an accurate point cloud that represents all objects. However, if you use the proposed smoothing operation based on integrated positional encoding that tries to smoothen the surfaces and hence intuitively makes surfaces a bit thicker, you might be able to get away with less dense sampling, too (but of course end up with smoothened surfaces). If you use an equivalent NGP-style hybrid representation that is faster in querying the field, even a dense enough sampling might not take too much time and be viable.
